name: Deploy Static Content to GitHub Pages

on:
  # Triggers the workflow on push to the master branch
  push:
    branches:
      - master  # Change this to main if that's your default branch

  # Allows manual trigger of the workflow
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN for deployment to GitHub Pages
permissions:
  contents: read    # To read the contents of the repository
  pages: write      # To write to GitHub Pages
  id-token: write   # To enable the use of authentication tokens

# Allows only one concurrent deployment, but doesn't cancel in-progress jobs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL of the deployed site
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the job

    steps:
      # Checkout the repository to get access to your files
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup GitHub Pages environment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload the entire repository as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Upload everything in the root directory of the repository

      # Deploy the static content to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
